Assignment1 @A-Tanner
IntelliTect-Samples/EWU-CSCD379-2022-Spring pull request #12
Opened 2022-04-12 02:53 UTC by Disciple4GIT

2022-04-13 05:04 UTC, hewrtarkhany commented
can you include the URL link for your website?

2022-04-13 05:06 UTC, hewrtarkhany requested changes

2022-04-13 05:06 UTC, hewrtarkhany commented on wordle-web/pages/game.vue
> +            <em><small>The world of real time competitive multiplayer Wordle is about to arrive...</small></em>
Nice, but I do not see your URL, so i can see if your webpage is working. thanks

2022-04-14 00:45 UTC, linhtran8699 reviewed
Everything looks good to me. Great job!

2022-04-24 20:04 UTC, mmwoodfo commented
In the future, just make sure that you are making a separate branch for your assignment, rather than making a PR using your main. Code changes showing up here in the PR should only be relevant to the assignment the PR is for.

Here is an example of a PR that uses an Assignment 1 branch: https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/pull/11

Great job!

2022-04-24 20:05 UTC, mmwoodfo reviewed
I don't see a link for the Azure app here!

2022-04-24 20:10 UTC, mmwoodfo commented
I think this is it? Found it in your actions pipeline output: https://thankful-water-09f62b010.1.azurestaticapps.net/

Make sure to include a link to this in the PR comments in the future.

2022-04-24 20:15 UTC, mmwoodfo commented
@Disciple4GIT I don't see a PR review. Let me know if you did one and I missed it.

2022-04-24 20:15 UTC, closed without merging