Assignment1
IntelliTect-Samples/EWU-CSCD379-2022-Spring pull request #14
Opened 2022-04-12 06:21 UTC by tnadalini

2022-04-14 01:20 UTC, DakotaCondos commented on wordle-web/pages/game.vue
> +          <v-btn color="primary" nuxt to="/game"> restart </v-btn>
Link to the main page is there and good use of `nuxt to="/game"` to restart. Is there a link to your azure website? I don't see it anywhere

2022-04-14 01:27 UTC, DakotaCondos commented on wordle-web/pages/game.vue
> +          <v-btn color="primary" nuxt to="/game"> restart </v-btn>
Also it looks like there are no changes to the YML file in the workflow.

2022-04-14 21:18 UTC, tremorris1999 requested changes
## Instructions

1. Create a Nuxt app ✅
   - Uses TypeScript ✅
   - Update Vue components to TypeScript ✅
   - Uses Vuetify ✅
   - Uses Jest ✅

3. Create a simple page called game.vue ✅
   - Page should have a card with a heading that with a clever name for the game ✅
   - some default placeholder body text ✅
   - and a button to take you back to the home page ✅
   - there should be a button the home page to access this page ✅

4. Check all the code into your repo fork ✅

5. Create a static web app in Azure ❌ (at least not in workflow or linked in some kind of readme or comment)
   - Create the container where your GitHub repo will deploy
   - Link the site with your GitHub repo

6. Update the CI/CD pipeline ❌ (not shown as PR is right now)
   - Pipeline runs on each check in
   - Jest tests run and pass ❌
   - Nuxt app builds ❌
   - Nuxt app deploys to Azure ❌

7. Azure site works ❌ (needs a link at least)
   - Post your Azure URL in your readme.md file. Replace the URL in the readme with your URL. ❌

## Extra Credit

- Come up with up to three unique ideas for stories we could implement as part of our project. Post these in your readme.md. ❌
- One point per idea up to three points

2022-04-14 21:18 UTC, tremorris1999 commented on wordle-web/pages/index.vue
> +          <v-btn color="primary" nuxt to="/game"> Game </v-btn>
Links to game.vue!

2022-04-24 20:21 UTC, mmwoodfo commented
In the future, just make sure that you are making a separate branch for your assignment, rather than making a PR using your main. Code changes showing up here in the PR should only be relevant to the assignment the PR is for.

Here is an example of a PR that uses an Assignment 1 branch: https://github.com/IntelliTect-Samples/EWU-CSCD379-2022-Spring/pull/11

Great job!

2022-04-24 20:25 UTC, mmwoodfo commented on wordle-web/pages/game.vue
> +      </v-card-title>
```suggestion
      <v-card-title class="headline text-h1 justify-center">
        Monke
      </v-card-title>
```

Consider using the vuetify classes for setting text heading sizes: https://vuetifyjs.com/en/styles/text-and-typography/

2022-04-24 20:25 UTC, mmwoodfo commented on wordle-web/pages/game.vue
> +          </p>
```suggestion
            "You saved me...why?" - Monkey
            "mm...Monkey" - Master Oogway
```

You don't need to wrap this in a `<p>` tag

2022-04-24 20:25 UTC, mmwoodfo commented on wordle-web/pages/game.vue
> +          <hr class="my-3" />
Consider using the `v-divider` component here: https://vuetifyjs.com/en/components/dividers/

2022-04-24 20:26 UTC, mmwoodfo commented
Looks like your actions pipeline is failing on the deployment step. Did you set up an Aure website?

2022-04-24 20:27 UTC, closed without merging