Assignment3
IntelliTect-Samples/EWU-CSCD379-2022-Spring pull request #48
Opened 2022-05-11 00:11 UTC by hewrtarkhany

web azure link 
https://wordle-api.azurewebsites.net

swagger link 
https://wordle-api.azurewebsites.net/swagger/index.html

wordle link https://nice-river-0685dad0f.1.azurestaticapps.net

2022-05-12 05:38 UTC, dpeterson8 commented
Website looks good and is up and running!

2022-05-12 06:56 UTC, tremorris1999 requested changes
Overall it looks pretty solid. You set up your API correctly and are getting things to look nice! Doesn't seem setting the user name is possible yet, but I see code for it that isn't accessible yet. Looks like all the heavy-lifting is done, just needs a bit of work getting all the other features to appear on screen!

2022-05-12 06:56 UTC, tremorris1999 commented on wordle-web/components/CreateUser.vue
> + localStorage.setItem("player", JSON.stringify( user));
Awesome!

2022-05-15 23:07 UTC, mmwoodfo reviewed
Make sure you run linter before your submissions

2022-05-15 23:07 UTC, mmwoodfo commented on wordle-web/pages/game.vue
> +    <createUser :wordleGame="wordleGame" :dialog="showSaveScoreDialog" />
```suggestion
    <createUser :wordleGame="wordleGame" :dialog.sync="showSaveScoreDialog" />
```

When the property you are passing to a child component is going to be updated by the child, you want to make sure you specify that it should be kept in sync with the parent component.

2022-05-15 23:07 UTC, mmwoodfo commented on wordle-web/pages/game.vue
> +      <v-btn class="ml-2" @click="savePlayerScore"> Save Game </v-btn>
This should automatically prompt when the game is over, rather than having the user click it manually.

2022-05-15 23:07 UTC, mmwoodfo commented on Wordle.Api/Services/PlayerService.cs
> +    public class PlayerService
Did you write any unit tests for this?

2022-05-15 23:08 UTC, closed without merging