Assignment3
IntelliTect-Samples/EWU-CSCD379-2022-Spring pull request #56
Opened 2022-05-11 07:07 UTC by AntonioGomez12

website link: https://orange-flower-0da9ed11e.1.azurestaticapps.net

2022-05-12 04:33 UTC, NazariyPogo commented
I will review

2022-05-12 06:17 UTC, NazariyPogo reviewed
1. Create a leaderboard API Controller ❌✅

Create an endpoint that returns the top 10 scores (HttpGet) ✅
Results should include Name, average guesses, and number of games played ✅
Create an endpoint that allows for posting a score (HttpPost) with data in the body ✅
A new name should add a new record ✅
An existing name should update that record ✅
Save and load all data with Entity Framework to an Azure SQL database or LocalDb for debugging ✅
Class should be named "Player" and "Players" for the DbSet ✅ //named playersStats, but should be fine
Fields should be:
int PlayerId ✅
string Name ✅
int GameCount ✅
double AverageAttempts ✅
int AverageSecondsPerGame ✅(OPTIONAL)
The logic should reside in a service that is injected via dependency injection into the controller ✅
Set up CORS (Cross Origin Resource Sharing) ❌
2. Create a dialog for getting the user's name ✅ //I like your take on account creation

If we don't have the user's name, present the user with a dialog that allows them to type in their name ❌ //Option available but not presented on end of game
The users current name should show on the game page (upper right) ✅
This should be visible when setting/changing the name. It should change as the user types ✅
The user should be able to click on their name to change it (with the same dialog) ✅
Save the name in local storage and load it for the next game if it is set ❌ //Name resets every time I refresh
If the name is not set, display Guest as the name. ✅
Clicking on this allows for preemptive setting of the name before the end of the game ✅
Dialog must be persistent, doesn't close by clicking off the dialog ✅
3. Save the Score and Seconds to complete ✅

Save the score and time to complete in seconds at the end of the game if we have a name. ❌ //I dont see any posts after a game is over in the network
If the user hasn't set a name, save the score and seconds as "Guest". (Be sure to prompt first) ❌ //No prompt
Save should be done with an Axios Post ❌ //Needs to be finished
4. Create a Leaderboard Page ✅ //Looks good as a draft, just need records to confirm

Create a /leaderboard page in the application that shows the top scores ❌✅ //No records yet
Use Axios to call the leaderboard API ❌ // calls need to be fixed
Make a nice display of the returned data ✅ //looks like it'll be pretty
Add a link on the front page to access the leaderboard ✅
Add a link to the app bar to access the leaderboard ❌ //Need link in app bar to leaderboard
5. Unit testing ✅ //Tests look good

Tests for the service ❌✅
Integration tests for the controller ❌ (OPTIONAL)
6. Deploy site to Azure ✅

Deploy API site with Github Action to Azure Web App ✅
Unit Tests should run on build ✅
Add API Base URL replacement to front end project via secret ❌ //Pls do this like we did in class, helped me a lot
Extra Credit
Unit testing on the client side (3) ❌
Animate the leaderboard (3) ❌
Create a logo (3) ❌✅
Add Average Seconds to win in score (3) ✅

2022-05-12 06:17 UTC, NazariyPogo commented on .github/workflows/azure-static-web-apps-orange-flower-0da9ed11e.yml
> -
Adding env:
  API_URL: ${{secrets.yourSecretName}}
here like done in class will allow you to simplify the url entered in the axios call

2022-05-12 06:20 UTC, NazariyPogo commented
One more thing... That click noise... interesting choice... seems like spamming it should come with a warning lol

2022-05-13 05:16 UTC, ZackWard-student commented
would be nice to have a link to your swagger server api as well.

2022-05-13 05:44 UTC, ZackWard-student commented
wordle-web/components/hsquid.png should probably be in the the static folder. Also it is a cursed image and should be removed from the project. (It also made my wife do a double take and question what I was doing)

2022-05-13 05:45 UTC, ZackWard-student commented
Neither front end nor back end compile...

2022-05-13 06:01 UTC, ZackWard-student requested changes
I like a lot of the ideas, but as is it does not compile.

2022-05-13 06:04 UTC, ZackWard-student commented
I am not sure what dbs you had stood up but there where no migration files for me to stand up the same ones.

2022-05-13 06:08 UTC, ZackWard-student commented
Don't forget to at least make it compile and run your linter before Meg sees it!

2022-05-20 02:35 UTC, mmwoodfo reviewed
Your backend code doesn't run because you're missing a Player class and the nuget package for entity framework. Additionally, the PR is technically a few minutes late, but I won't count that against you.

2022-05-20 02:35 UTC, mmwoodfo commented on .github/workflows/azure-static-web-apps-orange-flower-0da9ed11e.yml
> +name: Azure Static Web Apps CI/CD
It doesn't seem like your API is deployed correctly. Getting 404s on the website.

2022-05-20 02:35 UTC, mmwoodfo commented on Wordle.api/Data/AppDbContext.cs
> +        public DbSet<Player> PlayerStats { get; set; } = null!;
Looks like you don't have a player class?

2022-05-20 02:36 UTC, closed without merging